### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by jlevy44** [FrdVnW/dockerqda#2]
./RunDockeRQDA.sh
xauth:  file /tmp/.docker.xauth does not exist
xauth: (argv):1:  unable to read any entries from file "(stdin)"
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘gWidgetsRGtk2’ ...
** package ‘gWidgetsRGtk2’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
R session is headless; GTK+ not initialized.

(R:14): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Error : .onLoad failed in loadNamespace() for 'cairoDevice', details:
  call: fun(libname, pkgname)
  error: GDK display not found - please make sure X11 is running
Error : package ‘cairoDevice’ could not be loaded
ERROR: lazy loading failed for package ‘gWidgetsRGtk2’
* removing ‘/usr/local/lib/R/site-library/gWidgetsRGtk2’

**Comment by jlevy44** [comment]
I did find a conda workaround if you are interested

**Comment by nasifimtiazohi** [comment]
> I did find a conda workaround if you are interested

can you share the workaround? @jlevy44

**Comment by jlevy44** [comment]
It has been a while, I can get back to you... @ CurtisPetersen

**Comment by brooksambrose** [comment]
These [instructions](https://medium.com/@mreichelt/how-to-show-x11-windows-within-docker-on-mac-50759f4b65cb) worked for me:
- Open XQuartz and enable the "Allow connections from network clients" security setting
- Restart XQuartz
- Add two lines to `RunDockeRQDA.sh`:

```bash
#!/bin/bash
xhost + 127.0.0.1
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
docker run --rm -it --volume=$XSOCK:$XSOCK:rw \
       --volume=$XAUTH:$XAUTH:rw \
       --env="XAUTHORITY=${XAUTH}" \
       --env="DISPLAY" \
       --name whirl_wheels \
       --workdir=/root/ \
       --volume='pwd':/home/dockerqda/ \
       -e DISPLAY=host.docker.internal:0 \
       frdvnw/dockerqda:latest
```
